### ISSUE TITLE
In join as  a ground admin page  the flow is wrong

### ISSUE THREAD

**Issue by prathiusha22** [fssa-batch3/sandeep.prakash__web_project#4]
### Description of issue
In join as a ground admin page the flow is wrong 

### Expected result
it should first redirect to login page 

### Actual result
it is first redirecting to signup page.

### Steps to reproduce
1. Reorder the page as expected 
2. 
3. 

```
Path:      /pages/admin/adminsignup.html
Browser:   Chrome 111.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2--bookandplayz.netlify.app%2Fpages%2Fadmin%2Fadminsignup.html&os=Windows&os_version=10&browser=Chrome&browser_version=111.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #2](https://deploy-preview-2--bookandplayz.netlify.app/pages/admin/adminsignup.html)

**Comment by Sandeepsan97** [comment]
I have cleared my bug

**Comment by prathiusha22** [comment]
This issue "In join as a ground admin page the flow is wrong" is working good now.
