### ISSUE TITLE
Bug in friend request page

### ISSUE THREAD

**Issue by prathiusha22** [fssa-batch3/sandeep.prakash__web_project#5]
### Description of issue
When I gave the friend request multiple times to another user it send multiple request to that user but that should not happen actually.

### Expected result
It should send request only one time for that user.

### Actual result
But it's sending request multiple times.

### Steps to reproduce
1. When I mistakenly gave friend request for three times it was sended three times  friend request and send the request to the another user.
2. 
3. 

```
Path:      /pages/player/friendrequest.html
Browser:   Chrome 113.0.0.0 on Windows 10
Viewport:  1504 x 892 @1.5x
Language:  en-GB
Cookies:   Enabled
```

[Open in BrowserStack](https://www.browserstack.com/user/try-live?url=https%3A%2F%2Fdeploy-preview-2--bookandplayz.netlify.app%2Fpages%2Fplayer%2Ffriendrequest.html&os=Windows&os_version=10&browser=Chrome&browser_version=113.0&resolution=1504x892&speed=1&start=true&ref=netlify-source)

Submitted from [Netlify Deploy Preview #2](https://deploy-preview-2--bookandplayz.netlify.app/pages/player/friendrequest.html)

**Comment by Sandeepsan97** [comment]
I have cleared the issue

**Comment by prathiusha22** [comment]
When I gave the friend request multiple times to another user it send multiple request to that user but that should not happen actually. This issue has been cleared.
